# -*- coding: utf-8 -*-
"""구강 세그멘테이션 모델.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wzxraSV9mzc5vkFOYTPK08FzEkfvuY_q
"""

# ================================================================= #
# [LOWER] Mask R-CNN 치아 분할 학습 (안정성 + Best Model 저장)
# ================================================================= #
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
import torchvision
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from torchvision.models.detection.mask_rcnn import MaskRCNNPredictor
from PIL import Image
import os
import glob
from tqdm.auto import tqdm
import json
import numpy as np
import cv2
import sys

# Google Drive 마운트
if not os.path.exists('/content/drive'):
    from google.colab import drive
    drive.mount('/content/drive')

# ================================================================= #
# 1. 경로 및 설정 (LOWER 데이터로 변경됨)
# ================================================================= #
# JSON 파일 경로 (Lower)
JSON_REFERENCE_DIR = '/content/lowerdataset/train/lowerlabels'
# 원본 이미지 경로 (Lower)
ORIGINAL_IMAGE_DIR = '/content/lowerdataset/train/lowerimages'

# 학습 설정
IMAGE_SIZE = (512, 512)
BATCH_SIZE = 4
EPOCHS = 30
LEARNING_RATE = 0.005
NUM_TRAINING_FILES = 16000

# 저장 경로 설정
SAVE_DIR = '/content/drive/MyDrive/모프/학습모델/'
os.makedirs(SAVE_DIR, exist_ok=True)

# ★★★ 파일명 변경: upper -> lower ★★★
FINAL_SAVE_PATH = os.path.join(SAVE_DIR, '치아분할_MaskRCNN_lower_512_final.pth')
BEST_SAVE_PATH = os.path.join(SAVE_DIR, '치아분할_MaskRCNN_lower_512_best.pth')

# 장비 설정
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f">>> 작전 장비: {device} | 목표: LOWER Mask R-CNN 학습 (Workers=0)")

# ================================================================= #
# 2. Dataset 클래스 (동일함)
# ================================================================= #
class ToothInstanceDataset(Dataset):
    def __init__(self, img_dir, json_dir, num_files=None, width=512, height=512):
        self.img_dir = img_dir
        self.json_dir = json_dir
        self.width = width
        self.height = height
        self.imgs = []
        self.jsons = []

        print(f">>> 데이터 매칭 시작 (Lower)...")
        all_json_files = sorted(glob.glob(os.path.join(json_dir, '*.json')))

        if len(all_json_files) == 0:
            print("!!! 경고: JSON 파일이 없습니다. 경로를 확인하십시오 !!!")

        if num_files:
            all_json_files = all_json_files[:min(num_files, len(all_json_files))]

        for j_path in tqdm(all_json_files, desc="Matching"):
            base_name = os.path.splitext(os.path.basename(j_path))[0]
            img_path = os.path.join(img_dir, f"{base_name}.png")

            if os.path.exists(img_path):
                self.imgs.append(img_path)
                self.jsons.append(j_path)

        print(f">>> 총 {len(self.imgs)}쌍의 데이터 장전 완료!")

    def __len__(self): return len(self.imgs)

    def __getitem__(self, idx):
        img_path = self.imgs[idx]
        json_path = self.jsons[idx]

        # 이미지 로드
        img = cv2.imread(img_path)
        if img is None:
            return self.__getitem__((idx + 1) % len(self.imgs))

        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        orig_h, orig_w = img.shape[:2]

        with open(json_path, 'r') as f: data = json.load(f)

        boxes, masks, labels = [], [], []

        for tooth in data.get('tooth', []):
            seg = np.array(tooth.get('segmentation', []), dtype=np.int32)
            if len(seg) == 0: continue

            mask = np.zeros((orig_h, orig_w), dtype=np.uint8)
            cv2.fillPoly(mask, [seg], 1)

            x, y, w, h = cv2.boundingRect(seg)
            if w < 2 or h < 2: continue

            boxes.append([x, y, x+w, y+h])
            masks.append(mask)
            labels.append(1)

        img_resized = cv2.resize(img, (self.width, self.height))
        img_tensor = transforms.ToTensor()(img_resized)

        target_masks, target_boxes = [], []
        rx = self.width / orig_w
        ry = self.height / orig_h

        for i in range(len(masks)):
            m = cv2.resize(masks[i], (self.width, self.height), interpolation=cv2.INTER_NEAREST)
            target_masks.append(m)
            xmin = boxes[i][0] * rx
            ymin = boxes[i][1] * ry
            xmax = boxes[i][2] * rx
            ymax = boxes[i][3] * ry
            target_boxes.append([xmin, ymin, xmax, ymax])

        if len(target_boxes) > 0:
            boxes_tensor = torch.as_tensor(target_boxes, dtype=torch.float32)
            labels_tensor = torch.as_tensor(labels, dtype=torch.int64)
            masks_tensor = torch.as_tensor(np.array(target_masks), dtype=torch.uint8)

            image_id = torch.tensor([idx])
            area = (boxes_tensor[:, 3] - boxes_tensor[:, 1]) * (boxes_tensor[:, 2] - boxes_tensor[:, 0])
            iscrowd = torch.zeros((len(labels),), dtype=torch.int64)

            target = {}
            target["boxes"] = boxes_tensor
            target["labels"] = labels_tensor
            target["masks"] = masks_tensor
            target["image_id"] = image_id
            target["area"] = area
            target["iscrowd"] = iscrowd
        else:
            target = {
                "boxes": torch.zeros((0, 4), dtype=torch.float32),
                "labels": torch.zeros((0,), dtype=torch.int64),
                "masks": torch.zeros((0, self.height, self.width), dtype=torch.uint8),
                "image_id": torch.tensor([idx]),
                "area": torch.zeros((0,), dtype=torch.float32),
                "iscrowd": torch.zeros((0,), dtype=torch.int64)
            }
        return img_tensor, target

def collate_fn(batch): return tuple(zip(*batch))

# ================================================================= #
# 3. 모델 및 훈련 루프
# ================================================================= #
def get_model_instance_segmentation(num_classes):
    model = torchvision.models.detection.maskrcnn_resnet50_fpn(weights="DEFAULT")
    in_features = model.roi_heads.box_predictor.cls_score.in_features
    model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)
    in_features_mask = model.roi_heads.mask_predictor.conv5_mask.in_channels
    hidden_layer = 256
    model.roi_heads.mask_predictor = MaskRCNNPredictor(in_features_mask, hidden_layer, num_classes)
    return model

def train_mask_rcnn():
    dataset = ToothInstanceDataset(ORIGINAL_IMAGE_DIR, JSON_REFERENCE_DIR, num_files=NUM_TRAINING_FILES, width=IMAGE_SIZE[0], height=IMAGE_SIZE[1])

    if len(dataset) == 0:
        print("!!! 작전 중지: 로컬 경로에 데이터가 없습니다 !!!")
        return

    train_size = int(0.9 * len(dataset))
    val_size = len(dataset) - train_size
    train_set, val_set = torch.utils.data.random_split(dataset, [train_size, val_size])

    # num_workers=0
    train_loader = DataLoader(train_set, batch_size=BATCH_SIZE, shuffle=True, num_workers=0, collate_fn=collate_fn)

    model = get_model_instance_segmentation(num_classes=2)
    model.to(device)

    params = [p for p in model.parameters() if p.requires_grad]
    optimizer = torch.optim.SGD(params, lr=LEARNING_RATE, momentum=0.9, weight_decay=0.0005)
    lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=5, gamma=0.1)

    print(f"\n>>> 🚀 Mask R-CNN [LOWER] 훈련 개시! (총 {EPOCHS} 에폭)")

    best_loss = float('inf')

    for epoch in range(EPOCHS):
        model.train()
        epoch_loss = 0
        progress = tqdm(train_loader, desc=f"Ep {epoch+1}/{EPOCHS}", mininterval=10.0)

        for images, targets in progress:
            images = list(image.to(device) for image in images)
            targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

            loss_dict = model(images, targets)
            losses = sum(loss for loss in loss_dict.values())

            optimizer.zero_grad()
            losses.backward()
            optimizer.step()

            epoch_loss += losses.item()
            progress.set_postfix(loss=losses.item())

        lr_scheduler.step()

        avg_loss = epoch_loss / len(train_loader)
        print(f"✅ Ep {epoch+1} 완료 | 평균 Loss: {avg_loss:.4f}")

        if avg_loss < best_loss:
            best_loss = avg_loss
            torch.save(model.state_dict(), BEST_SAVE_PATH)
            print(f"   🏆 최고 성능 갱신! Best Model 저장됨: {os.path.basename(BEST_SAVE_PATH)}")

        if (epoch + 1) % 5 == 0:
            torch.save(model.state_dict(), FINAL_SAVE_PATH)
            print(f"   💾 중간 저장 완료")

    torch.save(model.state_dict(), FINAL_SAVE_PATH)
    print(f"\n>>> 모든 훈련 완료! 최종 모델 저장됨: {FINAL_SAVE_PATH}")

if __name__ == '__main__':
    train_mask_rcnn()

import os

# 1. 드라이브가 아직 마운트 안 되었다면 수행 (되어있다면 건너뜁니다)
if not os.path.exists('/content/drive'):
    from google.colab import drive
    drive.mount('/content/drive')

# --- 작전 경로 설정 ---

# 타겟 파일 경로 (구글 드라이브)
src_zip_path = '/content/drive/MyDrive/3.개방데이터/1.데이터/Training/1.원천데이터/5.lower.zip'
label_zip_path = '/content/drive/MyDrive/3.개방데이터/1.데이터/Training/2.라벨링데이터/5.lower.zip'

# 압축을 풀 로컬 목적지 (Colab 내부)
# 이름이 겹치지 않게 'images'와 'labels'로 폴더를 나눴습니다.
src_dest = '/content/lowerdataset/train/lowerimages'
label_dest = '/content/lowerdataset/train/lowerlabels'

# --- 작전 개시 (압축 해제) ---

print(f"작전 1: 원천 데이터(이미지) 해제 중... \n -> 목표지점: {src_dest}")
# 폴더 생성 (-p: 상위 폴더 없으면 같이 생성)
!mkdir -p "{src_dest}"
# 압축 해제 (-qq: 조용히, -d: 목적지 지정)
!unzip -qq "{src_zip_path}" -d "{src_dest}"

print(f"작전 2: 라벨링 데이터 해제 중... \n -> 목표지점: {label_dest}")
# 폴더 생성
!mkdir -p "{label_dest}"
# 압축 해제
!unzip -qq "{label_zip_path}" -d "{label_dest}"

print("======== 작전 성공! 모든 데이터 전개 완료! ========")