# -*- coding: utf-8 -*-
"""구강충치 탐지.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y6Rw2lFcOSpTP0EQCKKmKHPq1EpIsRa7
"""

!pip install opencv-python scikit-learn tensorflow

# ================================================================= #
# [Lower] 로컬 데이터 기반 충치 분류 모델 재학습 (Best Model 저장)
# ================================================================= #
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import models, transforms
from PIL import Image
import os
import glob
from tqdm.auto import tqdm
import numpy as np
import cv2
import json
import random

# 드라이브 마운트
if not os.path.exists('/content/drive'):
    from google.colab import drive
    drive.mount('/content/drive')

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f">>> 작전 장비: {device}")

# ================================================================= #
# 1. 설정 (Lower 로컬 경로 적용)
# ================================================================= #
# ★★★ [수정됨] 하악(Lower) 로컬 데이터 경로 ★★★
IMAGE_DIR = '/content/lowerdataset/train/lowerimages'
JSON_DIR = '/content/lowerdataset/train/lowerlabels'

# 모델 저장 경로
SAVE_DIR = '/content/drive/MyDrive/모프/학습모델/'
if not os.path.exists(SAVE_DIR):
    os.makedirs(SAVE_DIR, exist_ok=True)

# ★★★ [수정됨] 파일명 변경: upper -> lower ★★★
BEST_SAVE_PATH = os.path.join(SAVE_DIR, 'caries_classifier_lower_224_balanced_best.pth')
FINAL_SAVE_PATH = os.path.join(SAVE_DIR, 'caries_classifier_lower_224_balanced_final.pth')

# 학습 파라미터
IMAGE_SIZE = (224, 224)
BATCH_SIZE = 32
EPOCHS = 20
LEARNING_RATE = 1e-4
POS_WEIGHT_VALUE = 15.0
MAX_DATA_SIZE = 50000

# ================================================================= #
# 2. 리스트 생성 함수
# ================================================================= #
def create_train_list(img_dir, json_dir, max_size=50000):
    print(f">>> 📂 로컬 데이터 스캔 중... (Lower)")

    all_images = glob.glob(os.path.join(img_dir, "*.png"))

    if len(all_images) == 0:
        print("!!! 오류: 이미지 파일이 하나도 없습니다. 경로를 확인하세요!")
        return []

    valid_pairs = []
    for img_path in tqdm(all_images, desc="Pairing"):
        basename = os.path.splitext(os.path.basename(img_path))[0]
        json_path = os.path.join(json_dir, f"{basename}.json")

        if os.path.exists(json_path):
            valid_pairs.append({'image_path': img_path, 'json_path': json_path})

    print(f"   - 매칭된 파일 쌍: {len(valid_pairs)}개")

    if len(valid_pairs) > max_size:
        random.shuffle(valid_pairs)
        valid_pairs = valid_pairs[:max_size]
        print(f"   - {max_size}개로 데이터를 제한합니다.")

    return valid_pairs

# ================================================================= #
# 3. 데이터셋 클래스
# ================================================================= #
class CariesCropDataset(Dataset):
    def __init__(self, file_list, img_size):
        self.samples = []
        self.img_size = img_size

        print(f">>> 치아 크롭 데이터셋 구축 중...")

        for item in tqdm(file_list):
            img_path = item['image_path']
            json_path = item['json_path']

            try:
                with open(json_path, 'r') as f: data = json.load(f)
                for tooth in data.get('tooth', []):
                    gt_seg = np.array(tooth.get('segmentation', []), dtype=np.int32)
                    if len(gt_seg) == 0: continue
                    x, y, w, h = cv2.boundingRect(gt_seg)
                    decayed = 1 if tooth.get('decayed', False) else 0

                    self.samples.append({
                        'img_path': img_path, 'bbox': (x, y, w, h), 'label': decayed
                    })
            except: continue

        print(f">>> 총 학습용 치아 샘플: {len(self.samples)}개")

        self.transform = transforms.Compose([
            transforms.Resize(self.img_size),
            transforms.RandomHorizontalFlip(),
            transforms.RandomRotation(15),
            transforms.ColorJitter(brightness=0.2, contrast=0.2),
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
        ])

    def __len__(self): return len(self.samples)

    def __getitem__(self, idx):
        item = self.samples[idx]
        try:
            img = cv2.imread(item['img_path'])
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            x, y, w, h = item['bbox']
            crop = img[y:y+h, x:x+w]
            if crop.size == 0: raise ValueError("Empty crop")

            crop_pil = Image.fromarray(crop)
            img_tensor = self.transform(crop_pil)
            label_tensor = torch.tensor([item['label']], dtype=torch.float32)
            return img_tensor, label_tensor
        except:
            return self.__getitem__((idx + 1) % len(self.samples))

# ================================================================= #
# 4. 모델 및 학습 루프
# ================================================================= #
class CariesClassifier(nn.Module):
    def __init__(self, num_classes=1):
        super().__init__()
        try: self.base_model = models.resnet50(weights='DEFAULT')
        except: self.base_model = models.resnet50(weights='IMAGENET1K_V1')

        self.base_model.fc = nn.Sequential(
            nn.Linear(self.base_model.fc.in_features, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(512, num_classes)
        )
    def forward(self, x): return self.base_model(x)

def train_classifier():
    # 1. 로컬 파일 스캔 (Lower)
    file_list = create_train_list(IMAGE_DIR, JSON_DIR, MAX_DATA_SIZE)

    if not file_list: return

    # 2. 데이터셋 생성
    dataset = CariesCropDataset(file_list, IMAGE_SIZE)

    if len(dataset) == 0:
        print("!!! 추출된 치아 데이터가 없습니다.")
        return

    train_size = int(0.9 * len(dataset))
    val_size = len(dataset) - train_size
    train_set, val_set = torch.utils.data.random_split(dataset, [train_size, val_size])

    train_loader = DataLoader(train_set, batch_size=BATCH_SIZE, shuffle=True, num_workers=2, pin_memory=True)
    val_loader = DataLoader(val_set, batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)

    model = CariesClassifier(1).to(device)
    optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)

    pos_weight = torch.tensor([POS_WEIGHT_VALUE]).to(device)
    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)

    print(f"\n>>> 🚀 [Lower] 분류 모델 재학습 시작 (Best Model 저장)")

    best_val_loss = float('inf')

    for epoch in range(EPOCHS):
        model.train()
        train_loss = 0
        loop = tqdm(train_loader, desc=f"Ep {epoch+1}/{EPOCHS}", leave=False)

        for img, label in loop:
            img, label = img.to(device), label.to(device)
            pred = model(img)
            loss = criterion(pred, label)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            train_loss += loss.item()
            loop.set_postfix(loss=loss.item())

        # 검증
        model.eval()
        val_loss = 0
        tp, fn, fp = 0, 0, 0

        with torch.no_grad():
            for img, label in val_loader:
                img, label = img.to(device), label.to(device)
                out = model(img)
                val_loss += criterion(out, label).item()

                pred_prob = torch.sigmoid(out)
                predicted = (pred_prob > 0.5).float()

                is_caries = (label == 1)
                is_normal = (label == 0)
                tp += (predicted[is_caries] == 1).sum().item()
                fn += (predicted[is_caries] == 0).sum().item()
                fp += (predicted[is_normal] == 1).sum().item()

        avg_val_loss = val_loss / len(val_loader)
        recall = tp / (tp + fn + 1e-6)
        precision = tp / (tp + fp + 1e-6)

        print(f"✅ Ep {epoch+1} | Loss:{avg_val_loss:.4f} | ★Recall:{recall:.4f} | Prec:{precision:.4f}")

        # Best Model 저장
        if avg_val_loss < best_val_loss:
            best_val_loss = avg_val_loss
            torch.save(model.state_dict(), BEST_SAVE_PATH)
            print(f"   🏆 최고 성능 갱신! 저장됨: {os.path.basename(BEST_SAVE_PATH)}")

    # Final Model 저장
    torch.save(model.state_dict(), FINAL_SAVE_PATH)
    print(f"\n>>> 학습 완료! 최종 모델 저장됨: {FINAL_SAVE_PATH}")

if __name__ == '__main__':
    train_classifier()

import os

# 1. 드라이브가 아직 마운트 안 되었다면 수행 (되어있다면 건너뜁니다)
if not os.path.exists('/content/drive'):
    from google.colab import drive
    drive.mount('/content/drive')

# --- 작전 경로 설정 ---

# 타겟 파일 경로 (구글 드라이브)
src_zip_path = '/content/drive/MyDrive/3.개방데이터/1.데이터/Training/1.원천데이터/5.lower'
label_zip_path = '/content/drive/MyDrive/3.개방데이터/1.데이터/Training/2.라벨링데이터/5.lower.zip'

# 압축을 풀 로컬 목적지 (Colab 내부)
# 이름이 겹치지 않게 'images'와 'labels'로 폴더를 나눴습니다.
src_dest = '/content/lowerdataset/train/lowerimages'
label_dest = '/content/lowerdataset/train/lowerlabels'

# --- 작전 개시 (압축 해제) ---

print(f"작전 1: 원천 데이터(이미지) 해제 중... \n -> 목표지점: {src_dest}")
# 폴더 생성 (-p: 상위 폴더 없으면 같이 생성)
!mkdir -p "{src_dest}"
# 압축 해제 (-qq: 조용히, -d: 목적지 지정)
!unzip -qq "{src_zip_path}" -d "{src_dest}"

print(f"작전 2: 라벨링 데이터 해제 중... \n -> 목표지점: {label_dest}")
# 폴더 생성
!mkdir -p "{label_dest}"
# 압축 해제
!unzip -qq "{label_zip_path}" -d "{label_dest}"

print("======== 작전 성공! 모든 데이터 전개 완료! ========")