# -*- coding: utf-8 -*-
"""마스크사진 테스트.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jvTRAcyC_-PXZwxCwXjCGBYVQv6Wcrrs
"""

# ================================================================= #
# [수정된 정찰 작전] 학습된 U-Net 성능 눈으로 확인하기 (설계도 포함)
# ================================================================= #
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.nn.functional as F
import cv2
import numpy as np
import random
import os
from torchvision import transforms
from PIL import Image

# -------------------------------------------------------------
# 1. UNet 설계도 재확인 (이게 없어서 에러가 난 것이오!)
# -------------------------------------------------------------
class DoubleConv(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__(); self.double_conv = nn.Sequential(nn.Conv2d(in_channels, out_channels, 3, padding=1), nn.BatchNorm2d(out_channels), nn.ReLU(inplace=True), nn.Conv2d(out_channels, out_channels, 3, padding=1), nn.BatchNorm2d(out_channels), nn.ReLU(inplace=True))
    def forward(self, x): return self.double_conv(x)
class Down(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__(); self.maxpool_conv = nn.Sequential(nn.MaxPool2d(2), DoubleConv(in_channels, out_channels))
    def forward(self, x): return self.maxpool_conv(x)
class Up(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__(); self.up = nn.ConvTranspose2d(in_channels, in_channels // 2, kernel_size=2, stride=2); self.conv = DoubleConv(in_channels, out_channels)
    def forward(self, x1, x2):
        x1 = self.up(x1); diffY = x2.size()[2] - x1.size()[2]; diffX = x2.size()[3] - x1.size()[3]; x1 = F.pad(x1, [diffX // 2, diffX - diffX // 2, diffY // 2, diffY - diffY // 2]); x = torch.cat([x2, x1], dim=1); return self.conv(x)
class OutConv(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(OutConv, self).__init__(); self.conv = nn.Conv2d(in_channels, out_channels, kernel_size=1)
    def forward(self, x): return self.conv(x)
class UNet(nn.Module):
    def __init__(self, n_channels=3, n_classes=1):
        super(UNet, self).__init__(); self.inc = DoubleConv(n_channels, 64); self.down1 = Down(64, 128); self.down2 = Down(128, 256); self.down3 = Down(256, 512); self.down4 = Down(512, 1024); self.up1 = Up(1024, 512); self.up2 = Up(512, 256); self.up3 = Up(256, 128); self.up4 = Up(128, 64); self.outc = OutConv(64, n_classes)
    def forward(self, x):
        x1 = self.inc(x); x2 = self.down1(x1); x3 = self.down2(x2); x4 = self.down3(x3); x5 = self.down4(x4); x = self.up1(x5, x4); x = self.up2(x, x3); x = self.up3(x, x2); x = self.up4(x, x1); logits = self.outc(x); return logits

# -------------------------------------------------------------
# 2. 모델 준비 및 로드
# -------------------------------------------------------------
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = UNet(n_channels=3, n_classes=1).to(device)

# 저장된 최적 모델 경로 (파일명 확인 필!)
BEST_MODEL_PATH = '/content/drive/MyDrive/모프/학습모델/치아좌표탐지모델_unet_front_512.pth'

if os.path.exists(BEST_MODEL_PATH):
    model.load_state_dict(torch.load(BEST_MODEL_PATH, map_location=device))
    print(">>> 최적 모델 장착 완료! 성능 정찰을 시작하오.")
else:
    print(f"!!! 오류: 모델 파일이 없소! 경로를 확인하시오: {BEST_MODEL_PATH}")

model.eval()

# -------------------------------------------------------------
# 3. 데이터 하나 가져오기 (val_dataset이 없으면 직접 로드)
# -------------------------------------------------------------
# 이 코드는 val_dataset 변수가 살아있으면 그걸 쓰고, 없으면 파일 하나를 직접 엽니다.
try:
    if 'val_dataset' in globals():
        idx = random.randint(0, len(val_dataset)-1)
        image, mask = val_dataset[idx]
        print(">>> 메모리에 있는 데이터셋에서 샘플을 추출했소.")
    else:
        # 데이터셋 변수가 날아갔을 경우, 직접 파일 하나를 로드
        # (경로는 아까 성공했던 2.front와 마스크 폴더)
        IMG_DIR = '/content/drive/MyDrive/3.개방데이터/1.데이터/Training/1.원천데이터/2.front'
        MASK_DIR = '/content/drive/MyDrive/모프/탐지모델_데이터/마스크데이터_front'

        sample_file = random.choice(os.listdir(MASK_DIR))
        img_path = os.path.join(IMG_DIR, sample_file)
        mask_path = os.path.join(MASK_DIR, sample_file)

        # 변환 (512 Resize)
        tf = transforms.Compose([transforms.Resize((512, 512)), transforms.ToTensor()])

        image = Image.open(img_path).convert("RGB")
        mask = Image.open(mask_path).convert("L")

        image = tf(image)
        mask = tf(mask)
        mask = (mask > 0.5).float()
        print(f">>> 파일 직접 로드 성공: {sample_file}")

except Exception as e:
    print(f"!!! 데이터 로드 실패: {e}")
    # 더미 데이터 생성 (코드 테스트용)
    image = torch.zeros(3, 512, 512)
    mask = torch.zeros(1, 512, 512)

# -------------------------------------------------------------
# 4. 예측 및 시각화
# -------------------------------------------------------------
with torch.no_grad():
    input_tensor = image.unsqueeze(0).to(device)
    output = model(input_tensor)
    pred_mask = torch.sigmoid(output)
    pred_mask = (pred_mask > 0.5).float()

plt.figure(figsize=(12, 5))

# 원본
plt.subplot(1, 3, 1)
plt.title("Original Image")
plt.imshow(image.permute(1, 2, 0).numpy())
plt.axis('off')

# 정답 (Ground Truth)
plt.subplot(1, 3, 2)
plt.title("True Mask (Answer)")
plt.imshow(mask.squeeze(), cmap='gray')
plt.axis('off')

# 예측 (AI Prediction)
plt.subplot(1, 3, 3)
plt.title("AI Prediction (Result)")
plt.imshow(pred_mask.squeeze().cpu().numpy(), cmap='gray')
plt.axis('off')

plt.tight_layout()
plt.show()

print(">>> 정찰 완료. 맨 오른쪽 그림이 깔끔하게 나왔는지 확인하시오!")