# -*- coding: utf-8 -*-
"""마스크이미지데이터.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hvV6LPE6QCusvjeqCV61Fa_xbwBM5ima
"""

import os
import json
import cv2
import numpy as np
from tqdm import tqdm # 진행률 표시

# --- 작전 설정 ---
# 원본 JSON 파일들이 있는 폴더
JSON_DIR = '/content/drive/MyDrive/모프 구강 데이터/lower'
# 원본 이미지 파일들이 있는 폴더 (마스크 크기를 맞추기 위해 필요)
IMAGE_DIR = '/content/drive/MyDrive/3.개방데이터/1.데이터/Training/1.원천데이터/5.lower'

# ★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★
# ★★★ 수정된 부분: 저장소 경로 변경 ★★★
# 새로 생성될 마스크 이미지들을 저장할 폴더
MASK_OUTPUT_DIR = '/content/drive/MyDrive/모프/탐지모델_데이터/마스크데이터_lower/'
# ★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★

# --- 작전 준비 ---
os.makedirs(MASK_OUTPUT_DIR, exist_ok=True)
print(f"마스크 생성 작전을 개시합니다. 결과물은 '{MASK_OUTPUT_DIR}'에 저장됩니다.")

# --- 작전 개시 ---
# ★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★
# ★★★ 수정된 부분: 2000개 제한 해제 -> 모든 파일 처리 ★★★
json_files = sorted([f for f in os.listdir(JSON_DIR) if f.endswith('.json')])
print(f"총 {len(json_files)}개의 파일을 대상으로 마스크 생성을 시작합니다.")
# ★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★

for json_filename in tqdm(json_files, desc="마스크 생성 중"):
    json_path = os.path.join(JSON_DIR, json_filename)

    # 원본 이미지 경로 확인
    base_filename = os.path.splitext(json_filename)[0]
    image_path = os.path.join(IMAGE_DIR, f"{base_filename}.png")

    if not os.path.exists(image_path):
        # print(f"경고: {image_path} 이미지를 찾을 수 없어 건너뜁니다.") # 너무 많은 메시지를 피하기 위해 주석 처리
        continue

    try:
        # 원본 이미지를 읽어 크기 정보 확보
        image_bytes = np.fromfile(image_path, np.uint8)
        original_image = cv2.imdecode(image_bytes, cv2.IMREAD_COLOR)
        if original_image is None:
            continue
        height, width, _ = original_image.shape

        # 1. 원본 이미지와 똑같은 크기의 검은색 도화지(마스크)를 준비
        mask = np.zeros((height, width), dtype=np.uint8)

        # 2. JSON 파일을 읽어 치아 좌표를 가져옴
        with open(json_path, 'r', encoding='utf-8') as f:
            label_data = json.load(f)

        # 3. 각 치아의 좌표대로, 검은 도화지 위에 흰색으로 칠함
        for tooth in label_data.get('tooth', []):
            segmentation = np.array(tooth['segmentation'], dtype=np.int32)
            cv2.fillPoly(mask, [segmentation], (255)) # 255는 흰색

        # 4. 완성된 마스크 이미지를 파일로 저장
        mask_save_path = os.path.join(MASK_OUTPUT_DIR, f"{base_filename}.png")

        extension = os.path.splitext(mask_save_path)[1]
        result, encoded_img = cv2.imencode(extension, mask)
        if result:
            with open(mask_save_path, mode='w+b') as f:
                encoded_img.tofile(f)

    except Exception as e:
        # print(f"{json_filename} 처리 중 오류 발생: {e}") # 너무 많은 메시지를 피하기 위해 주석 처리
        pass

print("\n>>> 마스크 데이터셋 구축 작전 완료!")