# -*- coding: utf-8 -*-
"""충치탐지 검증

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wID7x_nadDZ_1DoziRuGrucrd54Ivc94
"""

import tensorflow as tf
import numpy as np
import cv2
import os
import json
import matplotlib.pyplot as plt
import sys
import glob

# --- 작전 설정 ---
MODEL_PATH = '/content/drive/MyDrive/모프/학습모델/caries_detection_model_final_tfdata.h5'
VALIDATION_IMAGE_DIR = '/content/drive/MyDrive/모프/검증데이터/front_n/'
VALIDATION_JSON_DIR = '/content/drive/MyDrive/모프/검증데이터/front/'
SUSPECTED_CARIES_SAVE_DIR = '/content/drive/MyDrive/모프/검증데이터/충치의심이미지/'
# ★★★ 시각화 결과 저장 경로 ★★★
VISUALIZATION_SAVE_DIR = '/content/drive/MyDrive/모프/검증데이터/검증결과_시각화/'

NUM_FILES_TO_TEST = 2000
IMAGE_SIZE = (128, 128)

# --- 작전 준비 ---
print(">>> 정예 모델을 전선에 배치합니다...")
try:
    model = tf.keras.models.load_model(MODEL_PATH)
    print(">>> 모델 배치 완료.")
except Exception as e:
    print(f"!!! 모델 로드 실패: {e}")
    sys.exit()

os.makedirs(SUSPECTED_CARIES_SAVE_DIR, exist_ok=True)
# ★★★ 시각화 결과 저장 폴더 생성 ★★★
os.makedirs(VISUALIZATION_SAVE_DIR, exist_ok=True)
print(f">>> 충치 의심 표적 확보 준비 완료. 저장경로: {SUSPECTED_CARIES_SAVE_DIR}")
print(f">>> 시각화 보고 준비 완료. 저장경로: {VISUALIZATION_SAVE_DIR}")


# --- 검증 대상 파일 목록 확보 ---
print(f">>> {VALIDATION_JSON_DIR} 경로에서 검증 대상 목록을 확보합니다...")
try:
    json_file_list = sorted(glob.glob(os.path.join(VALIDATION_JSON_DIR, '*.json')))[:NUM_FILES_TO_TEST]
    if not json_file_list: raise FileNotFoundError("!!! 작전 중지: 해당 경로에 JSON 파일이 없소.")
    print(f">>> 총 {len(json_file_list)}개의 검증 파일을 대상으로 작전을 시작합니다.")
except Exception as e:
    print(e)
    sys.exit()


def analyze_tooth_photo(image_path, coordinates_list, tooth_data_list):
    try:
        image_bytes = np.fromfile(image_path, np.uint8)
        original_image = cv2.imdecode(image_bytes, cv2.IMREAD_COLOR)
        if original_image is None: return None, None, None

        print(f"\n" + "="*50)
        print(f"--- {os.path.basename(image_path)} 분석 결과 보고 ---")

        preprocessed_teeth, cropped_teeth_for_saving = [], []

        for i, segmentation in enumerate(coordinates_list):
            segmentation = np.array(segmentation, dtype=np.int32)
            x, y, w, h = cv2.boundingRect(segmentation)
            if w == 0 or h == 0: continue

            mask = np.zeros(original_image.shape[:2], dtype=np.uint8)
            cv2.fillPoly(mask, [segmentation], (255))
            tooth_isolated = cv2.bitwise_and(original_image, original_image, mask=mask)
            tooth_cropped = tooth_isolated[y:y+h, x:x+w]

            cropped_teeth_for_saving.append(tooth_cropped)
            tooth_resized = cv2.resize(tooth_cropped, IMAGE_SIZE)
            preprocessed_teeth.append(tooth_resized)

        if not preprocessed_teeth: return None, None, None

        predictions = model.predict(np.array(preprocessed_teeth), verbose=0)

        correct_predictions, suspected_count = 0, 0
        for i, pred in enumerate(predictions):
            probability = pred[0] * 100
            verdict = "충치 의심" if probability > 50 else "정상"
            actual = "충치" if tooth_data_list[i]['decayed'] else "정상"
            result_mark = "O" if verdict == actual else "X"
            if result_mark == "O": correct_predictions += 1
            print(f"  ({result_mark}) 치아 #{i+1} (정답: {actual}): 예측 [{verdict}] (신뢰도: {probability:.2f}%)")

            if verdict == "충치 의심":
                suspected_count += 1
                save_filename = f"{os.path.splitext(os.path.basename(image_path))[0]}_tooth_{i+1}.png"
                save_path = os.path.join(SUSPECTED_CARIES_SAVE_DIR, save_filename)
                extension = os.path.splitext(save_path)[1]
                result, encoded_img = cv2.imencode(extension, cropped_teeth_for_saving[i])
                if result:
                    with open(save_path, mode='w+b') as f: encoded_img.tofile(f)

        if suspected_count > 0: print(f"  >>> 충치 의심 표적 {suspected_count}개 확보 완료.")
        total_teeth = len(predictions)
        accuracy = (correct_predictions / total_teeth) * 100 if total_teeth > 0 else 0
        print(f"  >>> 파일 내 정확도: {accuracy:.2f}% ({correct_predictions}/{total_teeth}개 정답)")

        # ★★★ 수정된 부분 1: 정확도, 좌표, 예측 결과를 모두 반환 ★★★
        return accuracy, coordinates_list, predictions

    except Exception as e:
        print(f"분석 중 오류 발생: {e}")
        return None, None, None

# --- 작전 개시 ---
total_accuracy_list = []
for json_path in json_file_list:
    base_filename = os.path.splitext(os.path.basename(json_path))[0]
    image_path = os.path.join(VALIDATION_IMAGE_DIR, f"{base_filename}.png")

    if not os.path.exists(image_path): continue

    try:
        with open(json_path, 'r', encoding='utf-8') as f:
            coordinate_data = json.load(f)

        if 'tooth' not in coordinate_data or not coordinate_data['tooth']: continue

        tooth_coordinates = [tooth['segmentation'] for tooth in coordinate_data['tooth']]
        tooth_data = coordinate_data['tooth']

        # ★★★ 수정된 부분 2: 함수에서 모든 정보를 받음 ★★★
        file_accuracy, returned_coords, returned_preds = analyze_tooth_photo(image_path, tooth_coordinates, tooth_data)

        if file_accuracy is not None:
            total_accuracy_list.append(file_accuracy)

            # ★★★ 수정된 부분 3: 시각화 보고서 생성 및 저장 ★★★
            image_bytes = np.fromfile(image_path, np.uint8)
            vis_image = cv2.imdecode(image_bytes, cv2.IMREAD_COLOR)

            for coords, pred in zip(returned_coords, returned_preds):
                if pred[0] > 0.5: # 충치 확률 50% 이상
                    segmentation = np.array(coords, dtype=np.int32)
                    x, y, w, h = cv2.boundingRect(segmentation)

                    # 붉은색(BGR -> 0,0,255) 사각형 그리기
                    cv2.rectangle(vis_image, (x, y), (x + w, y + h), (0, 0, 255), 2)

                    text = f"Cavity: {pred[0]*100:.1f}%"
                    cv2.putText(vis_image, text, (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)

            # 결과 이미지 저장
            vis_save_path = os.path.join(VISUALIZATION_SAVE_DIR, f"{base_filename}_result.png")
            extension = os.path.splitext(vis_save_path)[1]
            result, encoded_img = cv2.imencode(extension, vis_image)
            if result:
                with open(vis_save_path, mode='w+b') as f:
                    encoded_img.tofile(f)

    except Exception as e:
        print(f"!!! {os.path.basename(json_path)} 처리 중 오류 발생: {e}")

# --- 최종 종합 보고 ---
if total_accuracy_list:
    overall_accuracy = sum(total_accuracy_list) / len(total_accuracy_list)
    print("\n" + "="*70)
    print("### 최종 작전 결과 종합 보고 ###")
    print(f"총 {len(total_accuracy_list)}개 파일에 대한 분석을 완료했소.")
    print(f"전체 파일의 평균 정확도: {overall_accuracy:.2f}%")
    print("="*70)
else:
    print("\n!!! 분석을 완료한 파일이 없어 최종 보고를 할 수 없소.")