# -*- coding: utf-8 -*-
"""치아라벨링검증.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R1ZRPXXStodY-6hI1NBGSH6pu2_g3x-h
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import transforms
from PIL import Image
import numpy as np
import cv2
import os
import glob
from tqdm import tqdm
import sys

# ================================================================= #
# ★★★ 작전 설정 ★★★
# ================================================================= #

MODEL_PATH = '/content/drive/MyDrive/모프/학습모델/치아좌표탐지모델_unet_pytorch_augmented.pth'
VALIDATION_IMAGE_DIR = '/content/drive/MyDrive/모프/검증데이터/front_n/'
OUTPUT_DIR = '/content/drive/MyDrive/모프/검증데이터/정찰결과_시각화/'
DIAGNOSTIC_MASK_DIR = '/content/drive/MyDrive/모프/검증데이터/정찰결과_진단마스크/'

IMAGE_SIZE = (128, 128)

# ★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★
# ★★★ 수정된 부분: NUM_FILES_TO_VALIDATE 값을 None으로 변경 (전체 파일 검증) ★★★
NUM_FILES_TO_VALIDATE = None # 2000에서 None으로 변경
# ★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★


# ================================================================= #
# 1단계: U-Net 모델 설계도 준비 (변경 없음)
# ================================================================= #
class DoubleConv(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.double_conv = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True)
        )
    def forward(self, x):
        return self.double_conv(x)
class Down(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.maxpool_conv = nn.Sequential(
            nn.MaxPool2d(2),
            DoubleConv(in_channels, out_channels)
        )
    def forward(self, x):
        return self.maxpool_conv(x)
class Up(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.up = nn.ConvTranspose2d(in_channels, in_channels // 2, kernel_size=2, stride=2)
        self.conv = DoubleConv(in_channels, out_channels)
    def forward(self, x1, x2):
        x1 = self.up(x1); diffY = x2.size()[2] - x1.size()[2]; diffX = x2.size()[3] - x1.size()[3]
        x1 = F.pad(x1, [diffX // 2, diffX - diffX // 2, diffY // 2, diffY - diffY // 2])
        x = torch.cat([x2, x1], dim=1); return self.conv(x)
class OutConv(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(OutConv, self).__init__(); self.conv = nn.Conv2d(in_channels, out_channels, kernel_size=1)
    def forward(self, x):
        return self.conv(x)
class UNet(nn.Module):
    def __init__(self, n_channels=3, n_classes=1):
        super(UNet, self).__init__(); self.inc = DoubleConv(n_channels, 64); self.down1 = Down(64, 128); self.down2 = Down(128, 256); self.down3 = Down(256, 512); self.down4 = Down(512, 1024)
        self.up1 = Up(1024, 512); self.up2 = Up(512, 256); self.up3 = Up(256, 128); self.up4 = Up(128, 64); self.outc = OutConv(64, n_classes)
    def forward(self, x):
        x1 = self.inc(x); x2 = self.down1(x1); x3 = self.down2(x2); x4 = self.down3(x3); x5 = self.down4(x4)
        x = self.up1(x5, x4); x = self.up2(x, x3); x = self.up3(x, x2); x = self.up4(x, x1); logits = self.outc(x); return logits

# ================================================================= #
# 2단계: 작전 준비
# ================================================================= #
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(DIAGNOSTIC_MASK_DIR, exist_ok=True) # 진단용 폴더 생성

model = UNet(n_channels=3, n_classes=1).to(device)
try:
    model.load_state_dict(torch.load(MODEL_PATH, map_location=device))
    print(f">>> {MODEL_PATH}에서 정찰병 모델 로드 완료.")
except Exception as e:
    print(f"!!! 모델 로드 실패: {e}"); sys.exit()
model.eval()
preprocess = transforms.Compose([transforms.Resize(IMAGE_SIZE), transforms.ToTensor()])

# ================================================================= #
# 3단계: 정찰 임무 개시
# ================================================================= #
validation_files = sorted(glob.glob(os.path.join(VALIDATION_IMAGE_DIR, '*.png')))

# ★★★ 수정된 부분: NUM_FILES_TO_VALIDATE가 None이므로, if문이 False가 되어 전체 파일을 사용함 ★★★
if NUM_FILES_TO_VALIDATE is not None:
    validation_files = validation_files[:NUM_FILES_TO_VALIDATE]

print(f">>> 총 {len(validation_files)}개의 정찰 대상을 확인. 분석을 시작합니다...")

for img_path in tqdm(validation_files, desc="정찰 임무 수행 중"):
    try:
        # 한글 경로 처리를 위해 PIL 대신 cv2.imdecode 사용
        image_bytes = np.fromfile(img_path, np.uint8)
        original_image_cv = cv2.imdecode(image_bytes, cv2.IMREAD_COLOR)
        if original_image_cv is None:
            print(f"경고: {os.path.basename(img_path)} 파일을 로드할 수 없소.")
            continue

        # CV2 BGR 이미지를 PIL RGB 이미지로 변환 (모델 입력을 위해)
        original_image_pil = Image.fromarray(cv2.cvtColor(original_image_cv, cv2.COLOR_BGR2RGB))

        input_tensor = preprocess(original_image_pil).unsqueeze(0).to(device, dtype=torch.float32)

        with torch.no_grad():
            pred_logits = model(input_tensor)
            pred_probs = torch.sigmoid(pred_logits) # 0~1 사이의 확률값

        # ★★★ 진단용 '확신도 지도' 저장 ★★★
        prob_mask_numpy = pred_probs.squeeze().cpu().numpy() # (128, 128)
        prob_mask_uint8 = (prob_mask_numpy * 255).astype(np.uint8) # 0~1 확률을 0~255 회색조 값으로 변환
        diag_save_path = os.path.join(DIAGNOSTIC_MASK_DIR, f"{os.path.splitext(os.path.basename(img_path))[0]}_diagnostic.png")

        # 한글 경로 저장을 위해 imencode 사용
        extension = os.path.splitext(diag_save_path)[1]; result, encoded_img = cv2.imencode(extension, prob_mask_uint8)
        if result:
            with open(diag_save_path, mode='w+b') as f: encoded_img.tofile(f)


        # ★★★ 기존 후처리 및 시각화 ★★★
        pred_mask = (prob_mask_numpy > 0.5).astype(np.uint8) # 0.5 이상이면 1(치아), 아니면 0(배경)

        # 원본 이미지 크기로 마스크를 다시 확대
        pred_mask_resized = cv2.resize(pred_mask, (original_image_cv.shape[1], original_image_cv.shape[0]), interpolation=cv2.INTER_NEAREST)

        # 윤곽선(Contour) 찾기
        contours, _ = cv2.findContours(pred_mask_resized, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        # 원본 이미지(original_image_cv)에 윤곽선 그리기
        cv2.drawContours(original_image_cv, contours, -1, (0, 255, 0), 2) # 초록색, 2픽셀 두께

        # 시각화된 결과물 저장 (한글 경로 처리 포함)
        save_path = os.path.join(OUTPUT_DIR, f"{os.path.splitext(os.path.basename(img_path))[0]}_scouted.png")
        extension = os.path.splitext(save_path)[1]; result, encoded_img = cv2.imencode(extension, original_image_cv)
        if result:
            with open(save_path, mode='w+b') as f: encoded_img.tofile(f)

    except Exception as e:
        print(f"!!! {os.path.basename(img_path)} 처리 중 오류: {e}")

print("\n>>> 모든 정찰 임무 완료!")
print(f">>> 최종 보고서는 '{OUTPUT_DIR}' 폴더에서,")
print(f">>> 진단용 확신도 지도는 '{DIAGNOSTIC_MASK_DIR}' 폴더에서 확인할 수 있소.")